gg.jte.development-mode=true
spring.application.name=webbprojektSpringBoot26

spring.datasource.url=jdbc:postgesql://localhost:5432/webbprojektSpringBoot26
spring.datasource.username=user
spring.datasource.password=pw123

spring.jpa.hibernate.ddl-auto=none
spring.docker.compose.lifecycle-management=start_only
spring.devtools.livereload.enabled=true
