<!DOCTYPE html>
<html lang="sv-SE">
<head>
    <meta charset="utf-8">
    <title>Bokdatabas</title>
    <link rel="stylesheet" href="css/theme.css">
</head>
<body>

    <div class="hero">
        <h1>Välkommen till Bokprojektet</h1>
        <p>Detta är en bokdatabas som grundar sig på en specifik karaktär, tanken var att det bara skulle gå att lägga till fler böcker skrivna om samma karaktär och av samma författare men nu är det tillåtet att lägga till lite vad som helst.
        </p>
    </div>

    <div class="quote-box">
        "Karaktären är en muskulös man på 195cm och 110kg. Han är en före detta amerikansk militärpolis. Friheten att röra på sig är något som genomsyrar hans karaktär, han vandrar och liftar sig igenom USAs olika stater. Han står upp för dem svaga eller folk som råkat ut för orättvisa. Av många anses denna karaktär vara en riktig hjälte."
    </div>



    <div class="button-container">
        <a href="/books" class="big-button">Visa alla böcker</a>
        <a href="/books/create" class="big-button">Skapa en ny bok</a>
    </div>

</body>
</html>
