CREATE TABLE book
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    author       VARCHAR(255),
    description  VARCHAR(500),
    publish_date date,
    isbn         VARCHAR(255),
    CONSTRAINT pk_book PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT uc_book_isbn UNIQUE (isbn);
